version: '3'
services:
  node-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - apiURL=http://localhost:3001
    ports:
      - '3000:3000'
      - '2222:2222'
    container_name: node-client
  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    container_name: node-server
